-- Comprehensive Agricultural Knowledge Dataset for Vector Embeddings
-- Supporting 5 languages: English (en), Hindi (hi), Bengali (bn), Tamil (ta), Telugu (te)
-- Total estimated size: ~1MB of text data

-- ===========================================
-- CROP CULTIVATION PRACTICES (ENGLISH)
-- ===========================================

INSERT INTO agricultural_knowledge (title, content, category, subcategory, language, tags) VALUES

-- Rice Cultivation
('Advanced Rice Cultivation Techniques', 'Rice is the staple food for over half the world population. Advanced cultivation involves: 1) Land preparation with laser leveling for uniform water distribution, 2) Selecting high-yielding varieties like Basmati 370, PR-126, or hybrid varieties, 3) Direct seeding or transplanting 21-25 day old seedlings, 4) Maintaining 2-5cm water depth during vegetative growth, 5) Split application of nitrogen (50% basal, 25% at tillering, 25% at panicle initiation), 6) Integrated pest management using pheromone traps, biological control, and need-based pesticide application, 7) Harvesting at 80% maturity when grains turn golden yellow, 8) Proper drying to 14% moisture content for storage.', 'crops', 'rice', 'en', ARRAY['rice', 'cultivation', 'irrigation', 'fertilization', 'harvesting']),

('Wheat Production Management', 'Wheat is a major cereal crop requiring specific management: 1) Soil preparation with deep plowing followed by harrowing, 2) Sowing time optimization between October 15 - November 30 depending on variety, 3) Seed rate of 100-125 kg/hectare for timely sowing, 150 kg/hectare for late sowing, 4) Row spacing of 18-23 cm for optimal plant population, 5) Irrigation at critical stages: crown root initiation (20-25 DAS), tillering (40-45 DAS), jointing (60-65 DAS), flowering (85-90 DAS), and grain filling (105-110 DAS), 6) Balanced fertilization with 120:60:40 NPK kg/hectare, 7) Weed management through pre-emergence herbicides or manual weeding, 8) Disease control for rust, smut, and bunt through resistant varieties and fungicides.', 'crops', 'wheat', 'en', ARRAY['wheat', 'sowing', 'irrigation', 'fertilization', 'disease-management']),

('Maize Farming Best Practices', 'Maize cultivation for maximum yield: 1) Field preparation with deep plowing and formation of ridges and furrows, 2) Hybrid seed selection based on maturity duration and local adaptability, 3) Sowing at 60x20 cm spacing for rainfed conditions, 75x20 cm for irrigated conditions, 4) Seed treatment with fungicides and insecticides, 5) Fertilizer application: 120:60:40 NPK kg/hectare with 25% nitrogen as basal, 50% at knee-high stage, 25% at tasseling, 6) Weed control through pre-emergence herbicides followed by intercultivation, 7) Irrigation at critical stages: knee-high, tasseling, and grain filling, 8) Pest management for stem borer, fall armyworm, and pink bollworm, 9) Harvesting when moisture content reaches 15-20%.', 'crops', 'maize', 'en', ARRAY['maize', 'corn', 'hybrid-seeds', 'pest-management', 'harvesting']),

-- Vegetable Cultivation
('Tomato Production Technology', 'Commercial tomato cultivation: 1) Nursery preparation in pro-trays or raised beds with sterilized soil mixture, 2) Variety selection based on market demand: determinate for processing, indeterminate for fresh market, 3) Transplanting 4-5 week old seedlings at 60x45 cm spacing, 4) Drip irrigation system installation for water and fertilizer efficiency, 5) Mulching with plastic or organic materials for moisture conservation and weed control, 6) Staking and pruning for indeterminate varieties, 7) Fertigation schedule: NPK through drip system in split doses, 8) IPM approach for pest control: yellow sticky traps, biological agents, and selective pesticides, 9) Disease management for early blight, late blight, and viral diseases, 10) Harvesting at breaker stage for long-distance transport, fully ripe for local markets.', 'crops', 'tomato', 'en', ARRAY['tomato', 'greenhouse', 'drip-irrigation', 'IPM', 'harvesting']),

('Potato Cultivation Management', 'Potato production systems: 1) Land preparation with deep plowing and ridging for proper drainage, 2) Seed potato selection: certified, disease-free tubers of 30-40g weight, 3) Pre-planting treatments: chitting for 10-15 days, fungicide treatment, 4) Planting at 60x20 cm spacing at 8-10 cm depth, 5) Irrigation management: light frequent irrigation to maintain soil moisture, 6) Fertilization: 120:80:100 NPK kg/hectare with organic manure, 7) Earthing up operations at 30 and 50 days after planting, 8) Pest control for potato tuber moth, aphids, and white grubs, 9) Disease management for late blight, early blight, and bacterial wilt, 10) Harvesting when plants turn yellow and skin becomes firm.', 'crops', 'potato', 'en', ARRAY['potato', 'seed-treatment', 'irrigation', 'earthing-up', 'storage']),

-- Fruit Cultivation
('Mango Orchard Management', 'Mango cultivation for commercial production: 1) Site selection with well-drained soil and protection from strong winds, 2) Variety selection based on market preference and climatic adaptation, 3) Planting at 10x10m spacing for regular varieties, 8x8m for dwarf varieties, 4) Training and pruning for proper canopy development, 5) Irrigation through drip or micro-sprinkler systems, 6) Nutrient management: organic manure + NPK fertilizers based on tree age, 7) Flowering induction through ethrel spray or stress management, 8) Pest management for fruit fly, mango hopper, and scale insects, 9) Disease control for anthracnose, powdery mildew, and bacterial canker, 10) Harvesting at physiological maturity for distant markets, tree-ripe for local consumption.', 'crops', 'mango', 'en', ARRAY['mango', 'orchard', 'pruning', 'fruit-fly', 'post-harvest']),

-- ===========================================
-- CROP CULTIVATION PRACTICES (HINDI)
-- ===========================================

('उन्नत धान की खेती की तकनीकें', 'धान दुनिया की आधी से अधिक आबादी का मुख्य भोजन है। उन्नत खेती में शामिल है: 1) समान पानी वितरण के लिए लेजर लेवलिंग के साथ भूमि तैयारी, 2) बासमती 370, पीआर-126, या हाइब्रिड किस्मों जैसी उच्च उत्पादन देने वाली किस्मों का चयन, 3) 21-25 दिन पुराने पौधों की सीधी बुआई या रोपाई, 4) वानस्पतिक वृद्धि के दौरान 2-5 सेमी पानी की गहराई बनाए रखना, 5) नाइट्रोजन का विभाजित प्रयोग (50% बेसल, 25% कल्ले निकलते समय, 25% बाली निकलते समय), 6) फेरोमोन ट्रैप, जैविक नियंत्रण, और आवश्यकता आधारित कीटनाशक प्रयोग के साथ एकीकृत कीट प्रबंधन, 7) 80% परिपक्वता पर कटाई जब दाने सुनहरे पीले हो जाएं, 8) भंडारण के लिए 14% नमी तक उचित सुखाना।', 'crops', 'rice', 'hi', ARRAY['धान', 'खेती', 'सिंचाई', 'उर्वरक', 'कटाई']),

('गेहूं उत्पादन प्रबंधन', 'गेहूं एक प्रमुख अनाज फसल है जिसके लिए विशिष्ट प्रबंधन की आवश्यकता होती है: 1) गहरी जुताई के बाद हैरो से मिट्टी तैयार करना, 2) किस्म के आधार पर 15 अक्टूबर - 30 नवंबर के बीच बुआई का समय अनुकूलन, 3) समय पर बुआई के लिए 100-125 किग्रा/हेक्टेयर, देर से बुआई के लिए 150 किग्रा/हेक्टेयर बीज दर, 4) इष्टतम पौधा संख्या के लिए 18-23 सेमी पंक्ति अंतर, 5) महत्वपूर्ण चरणों में सिंचाई: मुकुट जड़ निर्माण (20-25 दिन), कल्ले निकलना (40-45 दिन), गांठ बनना (60-65 दिन), फूल आना (85-90 दिन), और दाना भरना (105-110 दिन), 6) 120:60:40 एनपीके किग्रा/हेक्टेयर के साथ संतुलित उर्वरीकरण, 7) अंकुरण पूर्व शाकनाशी या मैनुअल निराई के माध्यम से खरपतवार प्रबंधन, 8) प्रतिरोधी किस्मों और कवकनाशी के माध्यम से रतुआ, स्मट, और बंट के लिए रोग नियंत्रण।', 'crops', 'wheat', 'hi', ARRAY['गेहूं', 'बुआई', 'सिंचाई', 'उर्वरक', 'रोग-प्रबंधन']),

('मक्का की खेती की सर्वोत्तम प्रथाएं', 'अधिकतम उत्पादन के लिए मक्का की खेती: 1) गहरी जुताई और मेड़ों और नालियों के निर्माण के साथ खेत तैयार करना, 2) परिपक्वता अवधि और स्थानीय अनुकूलन के आधार पर हाइब्रिड बीज चयन, 3) वर्षा आधारित स्थितियों के लिए 60x20 सेमी, सिंचित स्थितियों के लिए 75x20 सेमी अंतर पर बुआई, 4) कवकनाशी और कीटनाशक के साथ बीज उपचार, 5) उर्वरक प्रयोग: 120:60:40 एनपीके किग्रा/हेक्टेयर के साथ 25% नाइट्रोजन बेसल, 50% घुटने की ऊंचाई पर, 25% टैसलिंग पर, 6) अंकुरण पूर्व शाकनाशी और इंटरकल्टिवेशन के माध्यम से खरपतवार नियंत्रण, 7) महत्वपूर्ण चरणों में सिंचाई: घुटने की ऊंचाई, टैसलिंग, और दाना भरना, 8) तना छेदक, फॉल आर्मीवर्म, और गुलाबी सुंडी के लिए कीट प्रबंधन, 9) नमी की मात्रा 15-20% तक पहुंचने पर कटाई।', 'crops', 'maize', 'hi', ARRAY['मक्का', 'मकई', 'हाइब्रिड-बीज', 'कीट-प्रबंधन', 'कटाई']),

-- ===========================================
-- CROP CULTIVATION PRACTICES (BENGALI)
-- ===========================================

('উন্নত ধান চাষের কৌশল', 'ধান বিশ্বের অর্ধেকেরও বেশি জনসংখ্যার প্রধান খাদ্য। উন্নত চাষাবাদের মধ্যে রয়েছে: ১) সমান পানি বন্টনের জন্য লেজার লেভেলিং সহ জমি প্রস্তুতি, ২) বাসমতি ৩৭০, পিআর-১২৬, বা হাইব্রিড জাতের মতো উচ্চ ফলনশীল জাত নির্বাচন, ৩) সরাসরি বপন বা ২১-২৫ দিন বয়সী চারা রোপণ, ৪) উদ্ভিজ্জ বৃদ্ধির সময় ২-৫ সেমি পানির গভীরতা বজায় রাখা, ৫) নাইট্রোজেনের বিভক্ত প্রয়োগ (৫০% ভিত্তি, ২৫% কুশি অবস্থায়, ২৫% শিষ অবস্থায়), ৬) ফেরোমন ফাঁদ, জৈবিক নিয়ন্ত্রণ, এবং প্রয়োজন ভিত্তিক কীটনাশক প্রয়োগ সহ সমন্বিত কীট ব্যবস্থাপনা, ৭) ৮০% পরিপক্বতায় কাটা যখন দানা সোনালি হলুদ হয়, ৮) সংরক্ষণের জন্য ১৪% আর্দ্রতায় যথাযথ শুকানো।', 'crops', 'rice', 'bn', ARRAY['ধান', 'চাষ', 'সেচ', 'সার', 'ফসল কাটা']),

('গম উৎপাদন ব্যবস্থাপনা', 'গম একটি প্রধান খাদ্যশস্য যার জন্য নির্দিষ্ট ব্যবস্থাপনা প্রয়োজন: ১) গভীর চাষের পর হ্যারো দিয়ে মাটি প্রস্তুতি, ২) জাতের উপর ভিত্তি করে ১৫ অক্টোবর - ৩০ নভেম্বরের মধ্যে বপনের সময় অনুকূলন, ৩) সময়মতো বপনের জন্য ১০০-১২৫ কেজি/হেক্টর, দেরিতে বপনের জন্য ১৫০ কেজি/হেক্টর বীজের হার, ৪) সর্বোচ্চ উৎপাদনের জন্য ১৮-২৩ সেমি সারি দূরত্ব, ৫) গুরুত্বপূর্ণ পর্যায়ে সেচ: মূল গঠন (২০-২৫ দিন), কুশি নির্গমন (৪০-৪৫ দিন), গিঁট গঠন (৬০-৬৫ দিন), ফুল ফোটা (৮৫-৯০ দিন), এবং দানা পূরণ (১০৫-১১০ দিন), ৬) ১২০:৬০:৪০ এনপিকে কেজি/হেক্টর সহ সুষম সারপ্রয়োগ, ৭) অঙ্কুরোদগম পূর্ব আগাছানাশক বা হাতে আগাছা পরিষ্কারের মাধ্যমে আগাছা ব্যবস্থাপনা, ৮) প্রতিরোধী জাত এবং ছত্রাকনাশকের মাধ্যমে মরিচা, স্মাট, এবং বান্টের জন্য রোগ নিয়ন্ত্রণ।', 'crops', 'wheat', 'bn', ARRAY['গম', 'বপন', 'সেচ', 'সার', 'রোগ ব্যবস্থাপনা']),

-- ===========================================
-- CROP CULTIVATION PRACTICES (TAMIL)
-- ===========================================

('மேம்பட்ட நெல் சாகுபடி நுட்பங்கள்', 'நெல் உலக மக்கள்தொகையின் பாதிக்கும் மேலானவர்களின் முக்கிய உணவாகும். மேம்பட்ட சாகுபடியில் அடங்கியவை: 1) சீரான நீர் விநியோகத்திற்காக லேசர் லெவலிங் உடன் நிலம் தயாரித்தல், 2) பாஸ்மதி 370, பிஆர்-126, அல்லது கலப்பின வகைகள் போன்ற அதிக மகசூல் தரும் வகைகளை தேர்வு செய்தல், 3) நேரடி விதைப்பு அல்லது 21-25 நாள் பழைய நாற்றுகளை நடுதல், 4) வளர்ச்சி நிலையில் 2-5 செமீ நீர் ஆழத்தை பராமரித்தல், 5) நைட்ரஜனின் பிரிக்கப்பட்ட பயன்பாடு (50% அடிப்படை, 25% கிளை விடும் நேரத்தில், 25% கதிர் நிலையில்), 6) ஃபெரோமோன் பொறிகள், உயிரியல் கட்டுப்பாடு, மற்றும் தேவை அடிப்படையிலான பூச்சிக்கொல்லி பயன்பாடு உடன் ஒருங்கிணைந்த பூச்சி மேலாண்மை, 7) 80% முதிர்ச்சியில் அறுவடை செய்தல் தானியங்கள் தங்க மஞ்சளாக மாறும்போது, 8) சேமிப்பிற்கு 14% ஈரப்பதத்திற்கு சரியான உலர்த்துதல்।', 'crops', 'rice', 'ta', ARRAY['நெல்', 'சாகுபடி', 'நீர்ப்பாசனம்', 'உரம்', 'அறுவடை']),

('கோதுமை உற்பத்தி மேலாண்மை', 'கோதுமை ஒரு முக்கிய தானிய பயிர் தனித்துவமான மேலாண்மை தேவைப்படுகிறது: 1) ஆழமான உழவிற்கு பிறகு மண் தயாரிப்பு, 2) வகையின் அடிப்படையில் அக்டோபர் 15 - நவம்பர் 30 க்கு இடையில் விதைப்பு நேர மேம்படுத்தல், 3) சரியான நேரத்தில் விதைப்பிற்கு 100-125 கிலோ/ஹெக்டேர், தாமதமான விதைப்பிற்கு 150 கிலோ/ஹெக்டேர் விதை விகிதம், 4) அதிகபட்ச உற்பத்திக்கு 18-23 செமீ வரிசை இடைவெளி, 5) முக்கியமான கட்டங்களில் நீர்ப்பாசனம்: வேர் உருவாக்கம் (20-25 நாட்கள்), கிளை நிலை (40-45 நாட்கள்), முட்டு நிலை (60-65 நாட்கள்), பூத்தல் (85-90 நாட்கள்), மற்றும் தானிய நிரப்புதல் (105-110 நாட்கள்), 6) 120:60:40 என்பிகே கிலோ/ஹெக்டேர் உடன் சமநிலையான உர பயன்பாடு, 7) முளைப்பு முன் களை நாசினி அல்லது கையால் களை எடுத்தல் மூலம் களை மேலாண்மை, 8) எதிர்ப்பு வகைகள் மற்றும் பூஞ்சைக் கொல்லி மூலம் துரு, ஸ்மட், மற்றும் பன்ட் நோய் கட்டுப்பாடு।', 'crops', 'wheat', 'ta', ARRAY['கோதுமை', 'விதைப்பு', 'நீர்ப்பாசனம்', 'உரம்', 'நோய் மேலாண்மை']),

-- ===========================================
-- CROP CULTIVATION PRACTICES (TELUGU)
-- ===========================================

('అధునాతన వరి సాగు పద్ధతులు', 'వరి ప్రపంచ జనాభాలో సగానికి మించిన వారి ప్రధాన ఆహారం. అధునాతన సాగులో ఇవి ఉంటాయి: 1) సమానమైన నీటి పంపిణీ కోసం లేజర్ లెవలింగ్‌తో భూమి తయారీ, 2) బాస్మతి 370, పిఆర్-126, లేదా హైబ్రిడ్ రకాలు వంటి అధిక దిగుబడినిచ్చే రకాల ఎంపిక, 3) ప్రత్యక్ష విత్తనాలు లేదా 21-25 రోజుల మొలకల నాటడం, 4) వృక్ష వృద్ధి సమయంలో 2-5 సెం.మీ నీటి లోతు నిర్వహణ, 5) నత్రజని విభజిత వాడకం (50% మూల, 25% కొమ్మల వేళ, 25% వెంట్రుకల వేళ), 6) ఫెరోమోన్ ట్రాప్స్, జీవసంబంధమైన నియంత్రణ, మరియు అవసరం ఆధారిత పురుగుమందుల వాడకంతో సమగ్ర పురుగుల నిర్వహణ, 7) 80% పరిపక్వతలో కోత ధాన్యాలు బంగారు పసుపు రంగులోకి మారినప్పుడు, 8) నిల్వ కోసం 14% తేమ వరకు సరైన ఎండబెట్టడం।', 'crops', 'rice', 'te', ARRAY['వరి', 'సాగు', 'నీటిపారుదల', 'ఎరువులు', 'కోత']),

('గోధుమ ఉత్పాదన నిర్వహణ', 'గోధుమ ఒక ప్రధాన ధాన్య పంట ప్రత్యేక నిర్వహణ అవసరం: 1) లోతైన దున్నిన తర్వాత మట్టి తయారీ, 2) రకం ఆధారంగా అక్టోబర్ 15 - నవంబర్ 30 మధ్య విత్తన సమయ అనుకూలత, 3) సమయానికి విత్తనం కోసం 100-125 కిలోలు/హెక్టేర్, ఆలస్య విత్తనం కోసం 150 కిలోలు/హెక్టేర్ విత్తన రేటు, 4) గరిష్ఠ ఉత్పాదనకు 18-23 సెం.మీ వరుస అంతరం, 5) కీలక దశలలో నీటిపారుదల: మూల ఏర్పాటు (20-25 రోజులు), కొమ్మల దశ (40-45 రోజులు), గాంటు దశ (60-65 రోజులు), పుట్టుట (85-90 రోజులు), మరియు ధాన్య నింపుట (105-110 రోజులు), 6) 120:60:40 ఎన్‌పికె కిలోలు/హెక్టేర్‌తో సమతులిత ఎరువుల వాడకం, 7) మొలకెత్తే ముందు కలుపు నిర్మూలకాలు లేదా చేతితో కలుపుల నిర్వహణ, 8) నిరోధక రకాలు మరియు శిలీంధ్రనాశకాలతో తుప్పు, స్మట్, మరియు బంట్ వ్యాధుల నియంత్రణ।', 'crops', 'wheat', 'te', ARRAY['గోధుమ', 'విత్తనం', 'నీటిపారుదల', 'ఎరువులు', 'వ్యాధుల-నిర్వహణ']),

-- ===========================================
-- PEST AND DISEASE MANAGEMENT
-- ===========================================

-- Integrated Pest Management
('Integrated Pest Management Strategies', 'IPM is a holistic approach combining multiple pest control methods: 1) Cultural control through crop rotation, intercropping with marigold, trap crops, and sanitation, 2) Biological control using natural predators like ladybird beetles, lacewings, parasitic wasps, and microbial agents like Bacillus thuringiensis, 3) Mechanical control through pheromone traps, light traps, and physical barriers, 4) Chemical control as the last resort using selective, low-toxicity pesticides with proper rotation to prevent resistance, 5) Monitoring through regular field scouting, yellow and blue sticky traps, and threshold-based intervention, 6) Resistance management by alternating pesticide modes of action and using tank mixtures, 7) Farmer education and training for proper identification of pests and beneficial insects.', 'pest-management', 'IPM', 'en', ARRAY['IPM', 'biological-control', 'pheromone-traps', 'pesticide-rotation', 'threshold']),

-- Disease Management
('Plant Disease Diagnosis and Management', 'Effective disease management requires accurate diagnosis and timely intervention: 1) Visual symptoms identification: leaf spots, wilting, stunting, discoloration, and growth abnormalities, 2) Laboratory diagnosis using microscopy, serology, and molecular techniques for confirmation, 3) Cultural practices: crop rotation, sanitation, resistant varieties, and proper spacing for air circulation, 4) Chemical control: preventive and curative fungicide applications with proper timing and coverage, 5) Biological control using antagonistic microorganisms like Trichoderma, Pseudomonas, and Bacillus species, 6) Environmental manipulation: adjusting humidity, temperature, and irrigation to create unfavorable conditions for pathogens, 7) Quarantine measures to prevent introduction and spread of new diseases, 8) Record keeping for monitoring disease pressure and treatment efficacy.', 'diseases', 'management', 'en', ARRAY['disease-diagnosis', 'fungicides', 'biological-control', 'quarantine', 'monitoring']),

-- ===========================================
-- SOIL AND FERTILITY MANAGEMENT
-- ===========================================

('Soil Health Assessment and Improvement', 'Soil health is fundamental to sustainable agriculture: 1) Physical assessment: structure, texture, bulk density, water infiltration, and compaction levels, 2) Chemical analysis: pH, electrical conductivity, organic matter, available nutrients (NPK, secondary, and micronutrients), 3) Biological indicators: soil respiration, microbial biomass, enzyme activity, and earthworm population, 4) Improvement strategies: organic matter addition through compost, vermicompost, and crop residues, 5) Cover cropping with legumes and grasses to improve soil structure and nitrogen fixation, 6) Reduced tillage practices to maintain soil structure and increase water retention, 7) Balanced fertilization based on soil test recommendations and crop requirements, 8) Lime application to correct soil acidity and gypsum for alkali soils, 9) Bio-fertilizers containing nitrogen-fixing bacteria, phosphate-solubilizing bacteria, and mycorrhizal fungi.', 'soil', 'health', 'en', ARRAY['soil-testing', 'organic-matter', 'cover-crops', 'bio-fertilizers', 'pH-management']),

('Nutrient Management Planning', 'Scientific nutrient management for optimal crop nutrition: 1) Soil testing for baseline nutrient status and pH determination, 2) Crop nutrient requirement assessment based on target yield and nutrient uptake patterns, 3) Nutrient budgeting considering soil supply, organic sources, and fertilizer requirements, 4) 4R nutrient stewardship: Right source, Right rate, Right time, Right place, 5) Organic nutrient sources: farmyard manure, compost, vermicompost, green manure, and bio-fertilizers, 6) Inorganic fertilizer selection and timing: split application for nitrogen, basal application for phosphorus and potassium, 7) Micronutrient management through soil and foliar applications, 8) Precision agriculture tools: variable rate application, soil sensors, and satellite imagery for site-specific management, 9) Environmental considerations: minimizing leaching, runoff, and greenhouse gas emissions.', 'soil', 'fertility', 'en', ARRAY['soil-testing', '4R-stewardship', 'organic-fertilizers', 'precision-agriculture', 'environmental-protection']),

-- ===========================================
-- WATER MANAGEMENT AND IRRIGATION
-- ===========================================

('Efficient Irrigation Management', 'Water-efficient irrigation for sustainable agriculture: 1) Irrigation scheduling based on crop water requirement, soil moisture, and weather conditions, 2) Drip irrigation systems for precision water and fertigation delivery, 3) Sprinkler irrigation for uniform water distribution in field crops, 4) Mulching for moisture conservation and evaporation reduction, 5) Rainwater harvesting and storage in farm ponds and check dams, 6) Deficit irrigation strategies for water-scarce regions, 7) Soil moisture monitoring using tensiometers, soil sensors, and gravimetric methods, 8) Irrigation water quality assessment for salinity, sodicity, and chemical contamination, 9) Drainage systems for waterlogged areas and salt management, 10) Crop selection and variety choice based on water availability and drought tolerance.', 'water-management', 'irrigation', 'en', ARRAY['drip-irrigation', 'irrigation-scheduling', 'water-conservation', 'rainwater-harvesting', 'drought-tolerance']),

-- ===========================================
-- LIVESTOCK MANAGEMENT
-- ===========================================

('Dairy Cattle Nutrition and Management', 'Comprehensive dairy cattle management for optimal milk production: 1) Balanced nutrition with quality fodder: green fodder (20-25 kg), dry fodder (4-6 kg), and concentrate (1 kg per 2.5 kg milk), 2) Breeding management: artificial insemination, heat detection, and genetic improvement programs, 3) Health care: vaccination schedule, deworming, hoof trimming, and mastitis prevention, 4) Housing requirements: adequate space (3.5 sq.m per animal), ventilation, and cleanliness, 5) Milking hygiene: clean udder washing, proper milking technique, and rapid cooling, 6) Calf management: colostrum feeding, weaning strategies, and growth monitoring, 7) Record keeping: breeding, health, production, and financial records, 8) Pasture management: rotational grazing and fodder crop cultivation, 9) Waste management: biogas production and organic manure preparation.', 'livestock', 'dairy', 'en', ARRAY['dairy-nutrition', 'breeding', 'mastitis-prevention', 'milking-hygiene', 'record-keeping']),

('Poultry Production Management', 'Modern poultry farming for sustainable egg and meat production: 1) Housing systems: battery cages for layers, deep litter for broilers, and free-range for organic production, 2) Nutrition management: starter, grower, and finisher feeds with appropriate protein and energy levels, 3) Health management: vaccination programs, biosecurity measures, and disease prevention protocols, 4) Environmental control: temperature, humidity, ventilation, and lighting programs, 5) Breeding: selection for production traits, artificial insemination, and genetic improvement, 6) Egg handling: collection, cleaning, grading, and storage at optimal conditions, 7) Meat processing: humane slaughter, processing hygiene, and cold chain maintenance, 8) Waste management: litter composting and biogas production, 9) Marketing strategies: direct sales, cooperative marketing, and value addition.', 'livestock', 'poultry', 'en', ARRAY['poultry-housing', 'nutrition', 'vaccination', 'biosecurity', 'egg-handling']),

-- ===========================================
-- AGRICULTURAL TECHNOLOGY AND INNOVATION
-- ===========================================

('Precision Agriculture Technologies', 'Technology-driven farming for enhanced efficiency and sustainability: 1) GPS-guided tractors and machinery for precise field operations, 2) Variable rate technology for optimized input application based on field variability, 3) Remote sensing using satellites and drones for crop monitoring and yield estimation, 4) Soil sensors for real-time monitoring of moisture, nutrients, and pH, 5) Weather stations and forecasting systems for informed decision making, 6) Farm management software for record keeping, planning, and financial analysis, 7) Internet of Things (IoT) devices for automation and monitoring, 8) Artificial intelligence and machine learning for predictive analytics, 9) Robotic systems for planting, weeding, and harvesting, 10) Blockchain technology for supply chain traceability and food safety.', 'technology', 'precision-agriculture', 'en', ARRAY['GPS-guidance', 'variable-rate-technology', 'remote-sensing', 'IoT', 'artificial-intelligence']),

('Digital Agriculture and Smart Farming', 'Digital transformation in agriculture for the 21st century farmer: 1) Mobile applications for crop advisory, weather information, and market prices, 2) Cloud computing for data storage, processing, and accessibility, 3) Big data analytics for pattern recognition and decision support, 4) Autonomous vehicles and machinery for reduced labor dependency, 5) Sensor networks for comprehensive farm monitoring, 6) Decision support systems integrating multiple data sources, 7) E-commerce platforms for input procurement and produce marketing, 8) Digital financial services for credit access and insurance, 9) Virtual reality and augmented reality for training and education, 10) Cyber security measures for protecting farm data and systems.', 'technology', 'digital-agriculture', 'en', ARRAY['mobile-apps', 'cloud-computing', 'big-data', 'autonomous-vehicles', 'decision-support-systems']),

-- ===========================================
-- CLIMATE CHANGE AND ADAPTATION
-- ===========================================

('Climate Change Adaptation Strategies', 'Building resilience against climate change impacts: 1) Drought-tolerant crop varieties and stress-resistant cultivars, 2) Water conservation through micro-irrigation and rainwater harvesting, 3) Climate-smart agriculture practices for carbon sequestration, 4) Diversified farming systems to reduce risk and improve stability, 5) Early warning systems for weather-related hazards, 6) Crop insurance and risk management strategies, 7) Soil health improvement for better water retention and nutrient cycling, 8) Agroforestry systems for microclimate modification and additional income, 9) Greenhouse and protected cultivation for controlled environment, 10) Community-based adaptation programs and farmer knowledge networks.', 'climate', 'adaptation', 'en', ARRAY['drought-tolerance', 'water-conservation', 'climate-smart-agriculture', 'risk-management', 'agroforestry']),

-- ===========================================
-- POST-HARVEST MANAGEMENT AND VALUE ADDITION
-- ===========================================

('Post-Harvest Management and Processing', 'Reducing post-harvest losses and adding value to farm produce: 1) Timely harvesting at optimum maturity for maximum quality and shelf life, 2) Proper cleaning, grading, and sorting to remove damaged and inferior produce, 3) Appropriate drying methods: sun drying, mechanical drying, and solar drying, 4) Storage management: pest control, moisture monitoring, and temperature regulation, 5) Processing technologies: milling, oil extraction, and food processing for value addition, 6) Packaging in suitable materials for protection and marketing appeal, 7) Cold chain management for perishable commodities, 8) Quality control and food safety measures throughout the supply chain, 9) Marketing channels: direct marketing, farmer producer organizations, and e-commerce platforms, 10) Certification programs: organic, fair trade, and geographical indications for premium pricing.', 'post-harvest', 'processing', 'en', ARRAY['harvesting', 'drying', 'storage', 'processing', 'cold-chain', 'marketing']),

-- ===========================================
-- AGRICULTURAL ECONOMICS AND MARKETING
-- ===========================================

('Farm Economics and Financial Management', 'Economic principles for profitable and sustainable farming: 1) Cost of production analysis including fixed and variable costs, 2) Enterprise budgeting for different crops and livestock activities, 3) Break-even analysis to determine minimum production levels, 4) Cash flow management for seasonal income patterns, 5) Credit management: sources, terms, and repayment strategies, 6) Insurance coverage for crops, livestock, and farm assets, 7) Investment analysis for machinery, infrastructure, and technology adoption, 8) Market analysis and price forecasting for informed production decisions, 9) Value chain analysis to identify profit opportunities, 10) Record keeping and financial planning for long-term sustainability.', 'economics', 'financial-management', 'en', ARRAY['cost-analysis', 'budgeting', 'credit-management', 'insurance', 'market-analysis']),

('Agricultural Marketing and Supply Chain', 'Effective marketing strategies for better farm income: 1) Market research and demand analysis for crop selection and planning, 2) Quality standards and grading systems for premium pricing, 3) Direct marketing through farmers markets and community-supported agriculture, 4) Cooperative marketing for collective bargaining and reduced transaction costs, 5) Contract farming for assured markets and stable prices, 6) Online platforms and e-commerce for wider market reach, 7) Export opportunities and quality compliance for international markets, 8) Value addition through processing and branding, 9) Supply chain optimization for reduced costs and improved efficiency, 10) Government schemes and support programs for marketing assistance.', 'economics', 'marketing', 'en', ARRAY['market-research', 'quality-standards', 'cooperative-marketing', 'contract-farming', 'value-addition']);
